version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    
      filters:
        branches:
          only: circleci-project-setup
          
    steps:
      - add_ssh_key:
        fingerprints:
        - 
      - checkout
      - run: pip install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/
      - run: python service.py

workflows:
  main:
    jobs:
      - build
