version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
          
    steps:
      - checkout
      - run: sudo docker build -t treelib . 

workflows:
  main:
    jobs:
      - build
