version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      image: circleci/python:3.7.1
    working_directory: ~/treelib
    executor: python/default
    steps:
      - checkout
      - run:
        name:
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
