version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
          
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install rsync
      - add_ssh_keys:
          fingerprints:
          - "fd:50:4c:f8:54:2f:e7:fc:bd:8a:eb:8e:e5:02:5d:0d"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: pwd
      - run: rsync -avzhe ssh service.py ubuntu@$139.199.58.80:/data

workflows:
  main:
    jobs:
      - build
