version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    
    filters:
      branches:
        only: circleci-project-setup
          
    steps:
      - add_ssh_key:
        fingerprints:
        - "fd:50:4c:f8:54:2f:e7:fc:bd:8a:eb:8e:e5:02:5d:0d"
      - checkout
      - run: pip install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/
      - run: python service.py

workflows:
  main:
    jobs:
      - build
