version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
          
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install rsync
      - add_ssh_keys:
          fingerprints:
          - "fd:50:4c:f8:54:2f:e7:fc:bd:8a:eb:8e:e5:02:5d:0d"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: ls
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "circleci-project-setup" ]; then
              rsync -avce ssh build $SSH_USER@$SSH_IP:/data/corki-ui-web/
            else
              echo "Not master branch, dry run only"
            fi

workflows:
  main:
    jobs:
      - build
